<?php

return [
	'css'	=> [
		'bootstrap'			=> 'assets/app/css/bootstrap.css',
		'animate'			=> 'assets/app/css/animate.css',
		'font-awesome'		=> 'assets/app/css/font-awesome.min.css',
		'icon'				=> 'assets/app/css/icon.css',
		'font'				=> 'assets/app/css/font.css',
		'app'				=> 'assets/app/css/app.css',
		'datepicker'		=> 'assets/app/js/datepicker/datepicker.css',
		'jquery-treegrid'	=> 'assets/app/css/jquery.treegrid.css',
		'chosen'			=> 'assets/app/js/chosen/chosen.css',
		'redactor'			=> 'assets/app/js/redactor/redactor.css',
		'uploader'			=> 'assets/app/js/datagrid/dist/css/uploader.css',
		'home-banner-uploader' => 'assets/app/js/home-banner/uploader.css',
		'home-slider-uploader' => 'assets/app/js/home-slider/uploader.css',
		'jquery-ui'			=> 'assets/app/css/jquery-ui.css',
		'color-picker'		=> 'assets/app/js/color-picker/css/colorpicker.css',
		'lionade-uploader'	=> 'assets/app/js/lionade/file-manager/lionade-uploader.css',
		'datatables'		=> 'assets/css/dataTables.bootstrap.min.css',
		'morris'			=> 'assets/app/js/morris/morris.css',
	],
	'js'	=> [
		'jquery'						=> 'assets/app/js/jquery-2.1.1.min.js',
		'ajax-progress'					=> 'assets/app/js/jquery.ajax.progress.js',
		'redactor'						=> 'assets/app/js/redactor/redactor.min.js',
		'datagrid'						=> 'assets/app/js/datagrid/dist/datagrid.js',
		'detail'						=> 'assets/app/js/datagrid/dist/detail.js',
		'validate'						=> 'assets/app/js/datagrid/dist/validate.js',
		'disabler'						=> 'assets/app/js/datagrid/dist/disabler.js',
		'enabler'						=> 'assets/app/js/datagrid/dist/enabler.js',
		'form'							=> 'assets/app/js/datagrid/dist/form.js',
		'uploader'						=> 'assets/app/js/datagrid/dist/uploader.js',
		'home-banner-uploader'			=> 'assets/app/js/home-banner/uploader.js',
		'home-slider-uploader'			=> 'assets/app/js/home-slider/uploader.js',
		'lionade-uploader'				=> 'assets/app/js/lionade/file-manager/lionade-uploader.js',
		'bootstrap'						=> 'assets/app/js/bootstrap.js',
		'app'							=> 'assets/app/js/app.js',
		'jquery-slimscroll'				=> 'assets/app/js/slimscroll/jquery.slimscroll.min.js',
		'app-plugin'					=> 'assets/app/js/app.plugin.js',
		'bootstrap-datepicker'			=> 'assets/app/js/datepicker/bootstrap-datepicker.js',
		'jquery-treegrid'				=> 'assets/app/js/jquery-treegrid/jquery.treegrid.js',
		'jquery-treegrid.bootstrap3'	=> 'assets/app/js/jquery-treegrid/jquery.treegrid.bootstrap3.js',
		'chosen-jquery-min'				=> 'assets/app/js/chosen/chosen.jquery.min.js',
		'jquery-ui'						=> 'assets/app/js/jquery-ui/jquery.ui.js',
		'jquery-flot-min'				=> 'assets/app/js/charts/flot/jquery.flot.min.js',
		'jquery-flot-tooltip'			=> 'assets/app/js/charts/flot/jquery.flot.tooltip.min.js',
		'jquery-flot-resize'			=> 'assets/app/js/charts/flot/jquery.flot.resize.js',
		'jquery-flot-spline'			=> 'assets/app/js/charts/flot/jquery.flot.spline.js',
		'jquery-flot-pie'				=> 'assets/app/js/charts/flot/jquery.flot.pie.min.js',
		'jquery-flot-grow'				=> 'assets/app/js/charts/flot/jquery.flot.grow.js',
		'fabric'						=> 'assets/app/js/fabric/dist/fabric.min.js',
		'color-picker'					=> 'assets/app/js/color-picker/colorpicker.min.js',
		'datatables'					=> 'assets/js/dataTables.bootstrap.min.js',
		'jquery-datatables'				=> 'assets/js/jquery.dataTables.min.js',
		'price-format'					=> 'assets/js/jquery.price_format.2.0.min.js',
		'morris-raphael'				=> 'assets/app/js/morris/raphael-min.js',
		'morris'						=> 'assets/app/js/morris/morris.min.js',
	] 
];
